### ISSUE TITLE
Sleep issue

### ISSUE THREAD

**Issue by cstrouse** [ssakuh/ASUS-Z170-Maximus-VIII-HERO-6700k-OpenCore#2]
Sleep issues may be caused because you have enabled Thunderbolt 3 support. Many people run into issues with sleep once they enable TB3 (and your system doesn't even seem to need it enabled because you don't list any TB3 AICs as being installed). I have the Asus ThunderboltEX 3 and works properly for TB3 devices and for the LG Ultrafine 4k monitors but requires a few adjustments to the UEFI settings from what you provide.

**Comment by ssakuh** [comment]
please send a pull request with the required changes and I will merge it
